name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Thanks for creating your first issue to this repo. Hope you can keep contributing to make our project better. Have an Octotastic day!'' first issue'
          pr-message: 'Thanks for creating your first pull request to this repo. Hope you can keep contributing to make our project better. Have an Octotastic day!'' first pr'
